#!/usr/bin/env bash
# prompt-index.sh — regenerate a session log's machine-extracted prompt index (D29).
#
# Every prompt of a session, in order, with the timestamp the machine recorded. It is
# the only part of the record that cannot drift from what was actually said, which is
# why D29 makes it a default rather than a repair.
#
# It REPLACES any existing index rather than appending, because an index goes stale
# the moment the next prompt arrives — that is not a defect, it is what an index of a
# live session is. Run it again before finishing.
#
# Usage:  ./prompt-index.sh <session-log.md> [transcript.jsonl]
#         (transcript defaults to the newest under ~/.claude/projects/)
#
# The log is matched to its transcript by the `<!-- session: … -->` comment when a
# transcript is not named explicitly — the same key the guards use.

set -uo pipefail
log="${1:-}"
[ -f "$log" ] || { echo "usage: $0 <session-log.md> [transcript.jsonl]" >&2; exit 2; }

tr_path="${2:-}"
if [ -z "$tr_path" ]; then
  sid=$(head -10 "$log" | sed -n 's/.*<!-- *session: *\([0-9a-fA-F-]*\) *-->.*/\1/p' | head -1)
  if [ -n "$sid" ]; then
    tr_path=$(ls -t "$HOME"/.claude/projects/*/"$sid".jsonl 2>/dev/null | head -1)
  fi
  [ -n "$tr_path" ] || tr_path=$(ls -t "$HOME"/.claude/projects/*/*.jsonl 2>/dev/null | head -1)
fi
[ -f "$tr_path" ] || { echo "no transcript found for $log" >&2; exit 1; }

python3 - "$log" "$tr_path" <<'PY'
import json, sys, datetime, re

log, tpath = sys.argv[1], sys.argv[2]
HARNESS = ("<system-reminder>", "<command-name>", "<command-message>", "<command-args>",
           "<local-command-stdout>", "<local-command-stderr>", "<user-memory-input>",
           "[Request interrupted", "<task-notification>")
MARK = "## Prompt index — machine-extracted, authoritative"

def ptext(rec):
    c = (rec.get("message") or {}).get("content")
    if isinstance(c, str):
        s = c.strip()
    elif isinstance(c, list):
        if any(isinstance(e, dict) and e.get("type") == "tool_result" for e in c):
            return None
        s = " ".join(e.get("text") or "" for e in c
                     if isinstance(e, dict) and e.get("type") == "text").strip()
    else:
        return None
    return None if (not s or s.startswith(HARNESS)) else s

rows = []
for line in open(tpath, encoding="utf-8", errors="replace"):
    line = line.strip()
    if not line:
        continue
    try:
        r = json.loads(line)
    except Exception:
        continue
    if r.get("type") != "user":
        continue
    if r.get("isSidechain") or r.get("isMeta") or r.get("isCompactSummary"):
        continue
    t = ptext(r)
    if t is None:
        continue
    dt = None
    for fmt in ("%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%SZ"):
        try:
            dt = datetime.datetime.strptime(r.get("timestamp", ""), fmt)
            break
        except Exception:
            pass
    # Transcript stamps are UTC; session logs are local with the zone named (D5).
    stamp = (dt - datetime.timedelta(hours=4)).strftime("%Y-%m-%d %H:%M EDT") if dt else "unknown"
    rows.append("- `%02d` · %s · %s" % (len(rows) + 1, stamp, t.replace("\n", " ")[:78]))

body = open(log, encoding="utf-8").read()
cut = body.find(MARK)
if cut != -1:                                   # drop the previous index, header and all
    sep = body.rfind("\n---\n", 0, cut)
    body = body[:sep if sep != -1 else cut].rstrip() + "\n"

section = [
    "", "---", "", MARK, "",
    "Regenerated by `prompt-index.sh` from this session's transcript JSONL — **not**",
    "reconstructed. Every prompt, in order, with the time the machine recorded.",
    "",
    "**The `## P##` entries above are curated; their timestamps may be approximate**",
    "(D28). Where the two disagree, this table wins.",
    "",
] + rows + ["", "**%d prompts.**" % len(rows), ""]

open(log, "w", encoding="utf-8").write(body + "\n".join(section))
print("%s: %d prompts indexed" % (log, len(rows)))
PY
